spring:
  application:
    name: goodwill-gh-service
  profiles:
    active: dev   # 或者 pro
  flyway:
    enabled: false
    locations: classpath:db/migration
  datasource:
    goodwill-gh-service:
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:5432/goodwill_gh_service
      username: ${DATABASE_USERNAME}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.postgresql.Driver
  # redis连接配置
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      database: 0
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone=UTC:
    open-in-view: false
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
invitation:
  valid:
    days: ${INVITATION_VALID_DAYS:7}
